### ISSUE TITLE
Hashing of Strs.AbstractChar

### ISSUE THREAD

**Issue by bkamins** [JuliaString/Strs.jl#50]
Here is an example of problematic behavior:

```
julia> x = Str("12")
"12"

julia> c
1

julia> hash(c)
ERROR: UndefVarError: hash_uint64 not defined
Stacktrace:
 [1] hash(::Strs.ASCIIChr) at .\hashing.jl:5
```

as it calls `hash_uint64` which is not imported or qualified with `Base.` (and the method is called with two arguments which is invalid in ).

Whatever we do I think that hash should return the same hash as for corresponding `Char`.

**Comment by ScottPJones** [comment]
For consistency, yes, unfortunately that will incur a severe performance penalty on hashing `AbstractChar` types (because of the expensive conversion from a Unicode codepoint to the internal format of `Char`).
(It sure would be nice to get rid of that, and simplify the code in Base, by changing `Char`'s internal representation to be an `Int32` where non-negative values are valid Unicode codepoints, and the invalid/malformed ones that `Char` allows are all negative (using the current representation, that would fall out naturally).

**Comment by bkamins** [comment]
Actually I had the same concerns. The same thing is for `Str` type. The other way is to clearly state that *Strs.jl* is not compatibile with `String/Char` from base in terms of hashes. The consequence is that `Dict` and `Set` will consider mixed `String` and `Str` (the same with `Char` and `CodePoint`) as different. Which then should be clearly documented.

However, currently - unfortunately - Python beats Julia hands down with `Dict` or `Set` having `String` as key type and we definitely should have a fast implementation. Otherwise any serious NLP application of Julia will be inferior to Python (and I guess this is what you are targeting at with *Strs.jl* as a whole - right?).

**Comment by bkamins** [comment]
And here - caching of hashes (what I guess you are planning) is crucial. The other thing is string interning (I am not clear what are your plans here). But having those two things will hopefully make `Dict`/`Set` fast enough to beat Python 😄.

**Comment by ScottPJones** [comment]
I certainly do mean to beat Python!
I have a lot of ideas for much faster Dict / Set types (not just for Str type), that I was planning on implementing as soon as I get Strs basically working.
If possible, I'd also like to (with a PR and benchmarking) convince the core team to drop the current `Char` representation, and move to something like I described above (after I've shown though that `Str`/`CodePoint` is much much faster than `String`/`Char` 😀

**Comment by ScottPJones** [comment]
About string interning, I don't want to do that for the entire system (like `Symbol`), because then they would never get GCed.
Instead, for things like split, JSON or CSV parsing, or strings put in an optimized string Dict/Set, I'd use the `SubStr` part of `Str` for the strings returned.  That would be much faster and save a lot of memory, and once the entire string was no longer referenced, it would be GCed.

**Comment by ScottPJones** [comment]
I've been investigating, and hashing performance is incredibly slow for all `AbstractString` types, because they cause a conversion to `String` and then do the hash (iterating over the codepoints and presenting them to the hashing code as a sequence of UTF-8 bytes can be done with no allocations instead for generic string hashing).

**Comment by ScottPJones** [comment]
Should be fixed now (#52), please close if works now for you.

**Comment by bkamins** [comment]
Yes - such "semi-interning" is a nice option.
I had a look at `Str` definition now and have several questions to understand where you want to go:
* do I understand it correctly that actually there would be no need of `SubString` in the ecosystem (as they would be simply `Str` but with different bounds) - this would be excellent (now the distinction between `String` and `SubString{String}` is a bit problematic in Base e.g. if you want to put both in the same collection);
* it is not clear to me what is the purpose of `STR_DATA_VECTOR`; it would essentially enable mutation of `Str` if set to `true`, which I guess is not desirable (probably there are reasons but I need to understand them 😄 );
* why do you need `Cache` and `Hash` to be parameters of `Str`, why simply `Cache` is not `Bool` and `Hash` is not `UInt`?
* what is the target intended use of `SubStr`? Again maybe we can set what this is? If I understand it correctly (but maybe I do not) `substr` should allow us to avoid the need to use `SubString`, simply if I have a `Str` and I call `SubString` on it - a new `Str` is created with appropriate bounds and `cache` is cleared if needed - right?

The reason I ask all those questions is that it is very desirable (as I have noted above) to have only one concrete type in one use case (and those three additional type parameters might mess things up - but maybe not).

Here is an example of the problem (in a bit different case, but which came up the moment I started to test the package):

```
julia> x = ["Nazywam", "się", "Bogumił", "∀α≥β"]
4-element Array{String,1}:
 "Nazywam"
 "się"
 "Bogumił"
 "∀α≥β"

julia> Str.(x)
4-element Array{Strs.Str{T,Void,Void,Void} where T,1}:
 "Nazywam"
 "się"
 "Bogumił"
 "∀α≥β"
```

and actually the following call is needed:

```
julia> Strs._UCS2Str.(x)
4-element Array{_UCS2Str,1}:
 "Nazywam"
 "się"
 "Bogumił"
 "∀α≥β"
```

to get a type stable collection (otherwise we get all kinds of performance problems).

We can move this discussion to a separate issue if you prefer.

Regarding `hash` in Base - this is exactly what I meant - it is extremely inefficient there. I will have a look at #52.

**Comment by bkamins** [comment]
Initial issue fixed as expected 👍.

**Comment by bkamins** [comment]
Probably in the future efficiency should be improved. This is not critical as I would not expect hashing of `Char` a major use case (as opposed to strings). I would keep the issue open to remind us to improve the performance one day.

**Comment by ScottPJones** [comment]
> do I understand it correctly that actually there would be no need of SubString in the ecosystem (as they would be simply Str but with different bounds) - this would be excellent (now the distinction between String and SubString{String} is a bit problematic in Base e.g. if you want to put both in the same collection);

Well, Base SubString would need to be supported, but substrings of Str would be created using the SubStr field (at least, that is my intention, but I want to prove to myself that it will be better)

>it is not clear to me what is the purpose of STR_DATA_VECTOR; it would essentially enable mutation of Str if set to true, which I guess is not desirable (probably there are reasons but I need to understand them 😄 );

No, I am very careful never to use anybody else's vectors directly.
That was just while I was trying different implementation schemes, to see what performed the best.
I'll be removing that in the next update, since using a `String` for the storage seems to be working well.

>why do you need Cache and Hash to be parameters of Str, why simply Cache is not Bool and Hash is not UInt?

`Cache` is intended to hold cached string conversions, like Python does, i.e. a `UTF8Str` version of the string, or even `UTF16Str` version.  Note: since these are immutable structs, unlike Python, you can't have the cached version added and then visible everywhere, you'd need to do something and then save the new string with both the old and cached strings.

> what is the target intended use of SubStr? Again maybe we can set what this is? If I understand it correctly (but maybe I do not) substr should allow us to avoid the need to use SubString, simply if I have a Str and I call SubString on it - a new Str is created with appropriate bounds and cache is cleared if needed - right?

I'd thought the `SubStr` field would hold either a UnitRange, or maybe some packed UInt type, big enough to hold the offset (in bytes) and number of bytes or maybe codeunits of the substring.

> The reason I ask all those questions is that it is very desirable (as I have noted above) to have only one concrete type in one use case (and those three additional type parameters might mess things up - but maybe not).

Not necessarily.  There is a lot of new support for small Union types now on master, so the idea is that people would really normally always use the `UniStr` type, which is actually a Union type, and only use other types such as `ASCIIStr` if they know for sure they only have ASCII strings.

Note: you used one of the `_xxxStr` types in your example, but those types are not exported, and are only for internal use - `_LatinStr` actually means that at least 1 character is between 0x80 and 0xff, `_UCS2Str` means that at least one is between 0x100 and 0xffff, and `_UTF32Str` means one is between 0x10000 and 0x10ffff.
This allows a lot of optimizations when comparing UniStr strings.

> We can move this discussion to a separate issue if you prefer.
Yes, this part was rather exploratory on my part, I'm investigating the performance issues around the new Union type support.

> Regarding hash in Base - this is exactly what I meant - it is extremely inefficient there. I will have a look at #52.

I do know how to take care of it, it really should be done in base for most `AbstractStrings`, with a few optimized methods in `Strs.jl` for the cases where the string is already `UTF-8` compatible (i.e. `ASCIIStr` and `UTF8Str`).

**Comment by bkamins** [comment]
Thank you. There are several issues here so I will open several separate.
