### ISSUE TITLE
Caching of hash

### ISSUE THREAD

**Issue by bkamins** [JuliaString/Strs.jl#55]
Do you have a clear idea how you want to implement caching of hashes?

I see two options (both have pros and cons - which we could discuss, but maybe there is a third way):
1. actually mutate immutable struct (this is possible as I am sure you know 😄)
2. make a field containing both `cached` and `hash` a mutable container (there are several options for this - probably the simplest is a `mutable struct`)

**Comment by ScottPJones** [comment]
This is still exploratory.  There are too many advantages to having the strings be immutable structs (allocation, storage in vectors/arrays, etc.).
You can't mutate the immutable, because there is no space allocated for the other fields (they simply don't exist)
My idea was more than things that would likely need the hash value, or a cached UTF8 value, would simply return a new string, that shares the first element, but has the extra field(s).
I.e. if you load in a UTF8 file with `readlines`, you make 1) big `Text1Str` or `UTF8Str` (depending on whether the entire thing is valid UTF8 or not) of the entire file. 2) you make a vector of UniStr (or UniStr), but with the cache field `Str{Union{Text1CSE, ASCIICSE, UTF8CSE},SubStr{UInt32}}` (for a < 4GB file). 3) set each element of the vector to a `Str{Union{ASCIICSE,_LatinCSE,_UCS2CSE,_UTF32CSE}},SubStr{UInt32},<:cachetype}`.

Then, when people do any processing on the strings, they get the faster performance (and ease of use) of fixed size characters and O(1) length operations, but if they ask for a UTF8 view of any of the string, no conversions back to UTF8 will need to be done, and there are not lots and lots of allocations.
Note: the ASCII substrings can just point directly into the original big string, and if there are any Latin, UCS2, or UTF32 substrings that need to be created, it can be handled in two passes, the first pass that is also splitting up the big string into and checking if each line is valid, can keep track of that, allowing it to also return a smaller Union type for the vector, possibly (say if the entire file was ASCII, or every line was _LatinStr, or _UCS2Str, or _UTF32Str, return it as a Vector{Str{ASCIICSE,SubStr{UInt32},Nothing,Nothing}} (i.e. a single concrete type).

**Comment by bkamins** [comment]
OK, I think now I get it (and I understand why you need all those signatures). But then you probably do not need `cache` field. You can simply check if `hash <: Nothing` to know if it is cached.
I understand that the bottom line is:
* have `Nothing` type of `hash` if hashing is not needed (and it saves memory - especially for small string)
* have some other type if `hash` is precomputed (e.g. by having `cache` argument in `UniStr` constructor)

And when constructing a string we decide if we want it to be cached or not. I guess this is OK, as usually we know if we want it cached. And you always can convert if needed. In such a case the only issue is if by default it should be cached or not.

Is this correct?

**Comment by ScottPJones** [comment]
I think you are misunderstanding (because I didn't have it documented well!) the purpose of the cache field.
That is for holding some cached version of the string, for example, the original source string (maybe as one of the "raw" types, `Text*Str` if it couldn't be validated, maybe `UTF8Str` or `UTF16Str` if it is valid).
The cached version would only be used for UTF8 or UTF16 or raw "views" of the string, or for outputting the string again, or passing it in UTF-8 or UTF-16 format to a library or another language (say JavaScript or Java, or the ICU library).

**Comment by bkamins** [comment]
Yes - I misunderstood the use of this field.
